### ISSUE TITLE
All teflo resource objects should implement __eq__ and __hash__ for equality testing

### ISSUE THREAD

**Issue by Dannyb48** [RedHatQE/teflo#111]
Currently all equality testing is based on a resources name attribute which is fine but is done upfront by the developer. The framework can keep using name if it wants or other parameters/attributes but it should be abstracted away to allow developers to just simply say `if asset_obj == asset_obj` or when checking if a resource is in a list by simply saying `if asset_obj in res_list` rather needing to access a particular attribute in the list. 

This comes into play when reloading rsource from tasks that were run in parallel by blaster.

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-354 has been created for this issue. Url : https://projects.engineering.redhat.com/browse/CCITCARBON-354

**Comment by rujutashinde** [comment]
fixed with #173
