### ISSUE TITLE
automate release process

### ISSUE THREAD

**Issue by JunqiZhang0** [RedHatQE/teflo#117]
1. Have the release workflow moved to master branch
2. Trigger workflow to do the bump version(once merge from develop to master, trigger it)
3. Use teflo notification plugin/ notify service to send out release email, also should in master

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-358 has been created for this issue. Url : https://projects.engineering.redhat.com/browse/CCITCARBON-358
