### ISSUE TITLE
Teflo best practice

### ISSUE THREAD

**Issue by JunqiZhang0** [RedHatQE/teflo#155]
We should have an Teflo best practice documented. It should cover from end to end. How to use results.yml, how to store ansible playbooks, how to do inclusion

**Comment by rujutashinde** [comment]
There is a page for this, but its not updated for the recent changes. So yes new changes should be added there https://teflo.readthedocs.io/en/latest/users/best_practices.html

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-382 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-382

**Comment by rujutashinde** [comment]
not going to work on this ticket as the project is being put in maintenance
