### ISSUE TITLE
Running `teflo validate` fails with 'skip-fail' KeyError

### ISSUE THREAD

**Issue by dfrazzette** [RedHatQE/teflo#171]
ISSUE: When running `teflo validate -s $TEFLO_SDF` (where $TEFLO_SDF is scenario.yml file), the task returns an error.

EXPECTED RESULT: The specified scenario is validated and the Teflo step passes.

ACTUAL RESULT: The task fails with error:
`...
File "/home/dfrazzet/gitlab/mock-rhel/venv/lib/python3.7/site-packages/teflo/teflo.py", line 597, in exit_on_status
    and self._teflo_options['skip_fail'] is not True and state is 'FAILED':
KeyError: 'skip_fail'`

(Ref repo [RedHatQE/teflo/teflo/teflo.py](https://github.com/RedHatQE/teflo/blame/588f94658cd7e490ef5111234c563e242a345735/teflo/teflo.py#L121-L122)). Output attached. [teflo_validate_error.txt](https://github.com/RedHatQE/teflo/files/7628611/teflo_validate_error.txt)

WORKAROUND: Running command `teflo run -t validate -s $TEFLO_SDF` is   ##successful.

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-396 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-396
