### ISSUE TITLE
pull requests against master branch(stable release branch) should trigger downstream tests

### ISSUE THREAD

**Issue by JunqiZhang0** [RedHatQE/teflo#175]
pull requests against master branch(stable release branch) should trigger downstream tests to run integration tests. Also this test should contains customers' scenario, too. The whole process should be automated, if pull request passed all downstream tests, it should be automatically merged and trigger the release. If not, should send msg to maintainers.

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-400 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-400

**Comment by rujutashinde** [comment]
not going to work on this ticket as the project is being put in maintenance
