### ISSUE TITLE
Unit tests should be idempotent

### ISSUE THREAD

**Issue by JunqiZhang0** [RedHatQE/teflo#188]
Right now the unit tests can be only run once. If you don't do cleanup. You can pass the unit tests

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-408 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-408

**Comment by rujutashinde** [comment]
not going to work on this ticket as the project is being put in maintenance
