### ISSUE TITLE
[DEPRECATION WARNING]: DISPLAY_SKIPPED_HOSTS option is deprecated

### ISSUE THREAD

**Issue by jbpratt** [RedHatQE/teflo#209]
Seeing warnings from teflo settings
```
[DEPRECATION WARNING]: DISPLAY_SKIPPED_HOSTS option, environment variables 
without ``ANSIBLE_`` prefix are deprecated, use the 
``ANSIBLE_DISPLAY_SKIPPED_HOSTS`` environment variable instead. This feature 
will be removed from ansible-core in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

https://github.com/RedHatQE/teflo/blame/60554294fcb641ed7216b1ae99b6ab3fa8f58abc/teflo/executors/ext/ansible_executor_plugin/ansible_executor_plugin.py#L232

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-433 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-433
