### ISSUE TITLE
Bump the minimum python version to 3.9

### ISSUE THREAD

**Issue by ryankwilliams** [RedHatQE/teflo#263]
Since Python 3.6 is no longer supported, the minimum python version should be bumped to 3.9. The latest version of ansible 7.0.0 that was released on 2022-11-23, sets a requirement of python 3.9 on the controller node.

https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_7.html#ansible-7-porting-guide

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-488 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-488
