### ISSUE TITLE
Fail to install teflo ssh-python dependency (python 3.11 support)

### ISSUE THREAD

**Issue by rnetser** [RedHatQE/teflo#267]
When trying to install teflo on env with python3.11 (default for fedora37),  `ssh-python` dependency fails (see #https://github.com/ParallelSSH/ssh-python/issues/57#issuecomment-1311877590 )

workaround - run in a venv with compatible python
[teflo_ssh_python.log](https://github.com/RedHatQE/teflo/files/10091683/teflo_ssh_python.log)

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-490 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-490

**Comment by rujutashinde** [comment]
closed with #284
