### ISSUE TITLE
Is there a plan for a v2.2.10 or v2.3.0 release?

### ISSUE THREAD

**Issue by ryankwilliams** [RedHatQE/teflo#268]
#264 was resolved on 2022-12-05 by https://github.com/RedHatQE/teflo/commit/5b968919a4303402a46a486b4b6357f8f58ab406. When will this commit be available in a new teflo release? Last release was back in November 2022. Just wondering because a CI pipeline my team currently maintains has been locking down the version of ansible used since this issue came about.

**Comment by dno-github** [comment]
@ryankwilliams We will have the teflo 2.3.0 release with this change by early next week

**Comment by ryankwilliams** [comment]
Thank you for the update
