### ISSUE TITLE
Bad tests in test_cli.py

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/teflo#47]
in tests/functional/test_cli.py the methods test_valid_run_var_file and test_valid_run_var_raw_json are invalid.

If you check the output of both tests, they complain that the file they're being passed (descriptor.yml) is invalid. Yet, teflo is returnning a `results.exit_code == 0`, so the test is passing. This means there are multiple problems:

1) Teflo should not be returning 0 when it encounters the error
2) This test isn't testing the templating at all

**Comment by rujutashinde** [comment]
closes with #48
