### ISSUE TITLE
There should be some "good first issue" for community developers/beginner developers

### ISSUE THREAD

**Issue by JunqiZhang0** [RedHatQE/teflo#85]
There should be some "good first issue" for community developers/beginner developers, just add the **good first** tag on the issue which is easy enough to be picked up by new team member/community developer. We could build a better community this way

**Comment by rujutashinde** [comment]
Jira ticket CCITCARBON-328 has been created for this issue. Url : https://projects.engineering.redhat.com/browse/CCITCARBON-328

**Comment by JunqiZhang0** [comment]
Added a good first issue, so close this one
