### ISSUE TITLE
bkr: support `--ks-append` for provisioner plugin

### ISSUE THREAD

**Issue by jbpratt** [RedHatQE/teflo#97]
We often want to just append on a small set of commands onto the existing kickstart file that is provided (if existing). Rather than requiring the entire thing, we can make use of the [kickstart append command option] on the beaker client.

```
bkr workflow-simple \
  --whiteboard="example" \
  --family="RedHatEnterpriseLinux8" \
  --tag="RELEASED" \
  --variant="BaseOS" \
  --arch="x86_64" \
  --ks-append="
reqpart
part /boot --recommended
part pv.rhel --grow
volgroup ${vg_name} pv.rhel
logvol /    --vgname=${vg_name} --name=root --size=1 --grow
logvol swap --vgname=${vg_name} --name=swap --recommended
" \
  --task="/distribution/check-install" \
  --machine="${PROVISIONING_HOST}" \
  --debug \
  --prettyxml \
  --wait
```

[kickstart append command option]: https://beaker-project.org/docs/man/bkr.html#cmdoption-bkr-ks-append

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-347 has been created for this issue. Url : https://projects.engineering.redhat.com/browse/CCITCARBON-347
